server:
  port: 8083
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/storage
    username: root
    password: "|@8hq6^Ey"
  flyway:
    url: jdbc:mysql://localhost:3306/storage
    locations: filesystem:src/main/resources/db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}